#En local corre en docker -_-
spring:
  profiles:
    active: dev
  application:
    name: oc

  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_NAME:oc};encrypt=false;trustServerCertificate=true
    username:  ${DB_USER:oc_user}
    password: ${DB_PASSWORD:VillaOc2026}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: pepecuentacuentos36@gmail.com
    password: okmz ljgn nrjm xvpx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      com.kong.oc: DEBUG
      org.springframework: DEBUG

app:
  frontend-base-url: http://localhost:4200
  email:
    from: pepecuentacuentos36@gmail.com
  activation:
    expiration-hours: 24
  purchase-order:
    pdf:
      storage-path: ${PURCHASE_ORDER_PDF_STORAGE_PATH:purchase-order-pdfs}
      company-name: ${PURCHASE_ORDER_COMPANY_NAME:GRUPO KONG S.A.C.}
      company-ruc: ${PURCHASE_ORDER_COMPANY_RUC:20601234567}
      company-address: ${PURCHASE_ORDER_COMPANY_ADDRESS:Av. Empresarial 456, Lima, Peru}
      generated-by: ${PURCHASE_ORDER_GENERATED_BY:Generado por Grupo Kong Sistemas}

server:
    port: 8080
